a = input('Digite algo: ')
print (f'O tipo primitivo desse valor é {type(a)}')
print (f'número: {a.isnumeric()}')
print (f'letra: {a.isalpha()}')
print('alfanumérico', a.isalnum())
print ('minúscula:', a.islower())
print ('maiúscula:', a.isupper())
print ('capitalizada:', a.istitle())
print ('decimal:', a.isdecimal())
print ('espaços:', a.isspace())